const fs=require('fs');const path=require('path');const crypto=require('crypto');const Database=require('better-sqlite3');
const cents=v=>{const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error('Enter a valid non-negative amount.');return Math.round(n*100)};
const qty=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<=0)throw Error('Quantity must be a positive whole number.');return n};
const id=v=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<=0)throw Error('Invalid record identifier.');return n};
const text=(v,max=200)=>String(v??'').trim().slice(0,max);
const requireText=(v,label)=>{const s=text(v);if(!s)throw Error(`${label} is required.`);return s};
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');return salt+':'+crypto.scryptSync(p,salt,64).toString('hex')};
const check=(p,h)=>{try{const [salt,stored]=h.split(':');return crypto.timingSafeEqual(Buffer.from(stored,'hex'),crypto.scryptSync(p,salt,64))}catch{return false}};
const iso=()=>new Date().toISOString();const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function createService(root){
 const appVersion=require('../package.json').version;
 fs.mkdirSync(root,{recursive:true});for(const sub of ['backups','logs','reports','uploads'])fs.mkdirSync(path.join(root,sub),{recursive:true});
 const dbPath=path.join(root,'medflow.sqlite'),backupDir=path.join(root,'backups');const existed=fs.existsSync(dbPath);const logError=(method,error)=>{try{fs.appendFileSync(path.join(root,'logs','medflow.log'),`${iso()} [${method}] ${String(error?.code||error?.message||'Unexpected failure').replace(/[\r\n]/g,' ').slice(0,400)}\n`)}catch{}};let db=new Database(dbPath);let sessions=new Map();
 // Before any schema write, take a consistent SQLite snapshot of older on-disk data.
 // VACUUM INTO includes committed WAL transactions; a plain file copy would not.
 if(existed){try{
   db.pragma('busy_timeout = 5000');
   if(!db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='settings'").get())throw Error('Existing database has no MedFlow settings table.');
   const r=db.prepare('SELECT value FROM settings WHERE key=?').get('appVersion');
   const prior=r?JSON.parse(r.value):'0.1.0';
   const compare=(v)=>String(v).split('.').map(x=>Number(x)||0);
   const a=compare(prior),b=compare(appVersion);
   if(a.some((n,i)=>n>(b[i]||0)&&a.slice(0,i).every((v,j)=>v===(b[j]||0))))throw Error('This database was opened by a newer MedFlow version. Downgrading is blocked.');
   if(prior!==appVersion){
     if(db.pragma('integrity_check',{simple:true})!=='ok')throw Error('Existing database failed its integrity check.');
     const name=`medflow-preupgrade-${String(prior).replace(/[^a-zA-Z0-9]/g,'_')}-to-${appVersion.replace(/[^a-zA-Z0-9]/g,'_')}-${iso().replace(/[:.]/g,'-')}.sqlite`;
     const target=path.join(backupDir,name);
     db.prepare('VACUUM INTO ?').run(target);
     const verify=new Database(target,{readonly:true,fileMustExist:true});
     try{if(verify.pragma('integrity_check',{simple:true})!=='ok')throw Error('Pre-upgrade backup failed verification.')}finally{verify.close()}
   }
 }catch(e){logError('preUpgradeBackup',e);db.close();throw Error(`Unable to safely open MedFlow: ${e.message}. The existing database was not migrated.`)}}
 function open(){db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');db.pragma('busy_timeout = 5000');db.exec(`
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'Cashier',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,contact TEXT DEFAULT '',phone TEXT DEFAULT '',email TEXT DEFAULT '',address TEXT DEFAULT '',notes TEXT DEFAULT '',created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY,name TEXT NOT NULL,phone TEXT DEFAULT '',email TEXT DEFAULT '',address TEXT DEFAULT '',credit_limit INTEGER NOT NULL DEFAULT 0,balance INTEGER NOT NULL DEFAULT 0,notes TEXT DEFAULT '',created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,generic TEXT DEFAULT '',brand TEXT DEFAULT '',manufacturer TEXT DEFAULT '',category TEXT DEFAULT 'General',sku TEXT UNIQUE,barcode TEXT UNIQUE,form TEXT DEFAULT 'Other',strength TEXT DEFAULT '',unit TEXT DEFAULT 'unit',retail INTEGER NOT NULL DEFAULT 0,purchase INTEGER NOT NULL DEFAULT 0,reorder INTEGER NOT NULL DEFAULT 10,prescription INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,supplier_id INTEGER REFERENCES suppliers(id),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS batches(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),supplier_id INTEGER REFERENCES suppliers(id),batch_no TEXT NOT NULL,expiry TEXT NOT NULL,purchased_on TEXT NOT NULL,cost INTEGER NOT NULL,price INTEGER NOT NULL,initial_qty INTEGER NOT NULL,remaining INTEGER NOT NULL CHECK(remaining>=0),UNIQUE(product_id,batch_no,expiry));
 CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY,invoice_no TEXT NOT NULL UNIQUE,supplier_id INTEGER NOT NULL REFERENCES suppliers(id),date TEXT NOT NULL,total INTEGER NOT NULL,paid INTEGER NOT NULL,due INTEGER NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY,purchase_id INTEGER NOT NULL REFERENCES purchases(id),batch_id INTEGER NOT NULL REFERENCES batches(id),product_id INTEGER NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL,returned INTEGER NOT NULL DEFAULT 0,cost INTEGER NOT NULL,price INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY,invoice_no TEXT NOT NULL UNIQUE,customer_id INTEGER REFERENCES customers(id),date TEXT NOT NULL,subtotal INTEGER NOT NULL,discount INTEGER NOT NULL,tax INTEGER NOT NULL,total INTEGER NOT NULL,paid INTEGER NOT NULL,due INTEGER NOT NULL,method TEXT NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sale_items(id INTEGER PRIMARY KEY,sale_id INTEGER NOT NULL REFERENCES sales(id),product_id INTEGER NOT NULL REFERENCES products(id),batch_id INTEGER NOT NULL REFERENCES batches(id),quantity INTEGER NOT NULL,returned INTEGER NOT NULL DEFAULT 0,price INTEGER NOT NULL,cost INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,reference_id INTEGER NOT NULL,customer_id INTEGER REFERENCES customers(id),amount INTEGER NOT NULL,method TEXT NOT NULL,date TEXT NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY,date TEXT NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,amount INTEGER NOT NULL,method TEXT NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS purchase_returns(id INTEGER PRIMARY KEY,purchase_id INTEGER NOT NULL REFERENCES purchases(id),purchase_item_id INTEGER NOT NULL REFERENCES purchase_items(id),quantity INTEGER NOT NULL,amount INTEGER NOT NULL,refund INTEGER NOT NULL,credit_applied INTEGER NOT NULL,reason TEXT NOT NULL,date TEXT NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS returns(id INTEGER PRIMARY KEY,sale_id INTEGER NOT NULL REFERENCES sales(id),sale_item_id INTEGER NOT NULL REFERENCES sale_items(id),quantity INTEGER NOT NULL,amount INTEGER NOT NULL,refund INTEGER NOT NULL,credit_applied INTEGER NOT NULL,reason TEXT NOT NULL,date TEXT NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS movements(id INTEGER PRIMARY KEY,product_id INTEGER NOT NULL REFERENCES products(id),batch_id INTEGER NOT NULL REFERENCES batches(id),delta INTEGER NOT NULL,before_qty INTEGER NOT NULL,after_qty INTEGER NOT NULL,reason TEXT NOT NULL,reference TEXT NOT NULL,user_id INTEGER NOT NULL REFERENCES users(id),created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),action TEXT NOT NULL,entity TEXT NOT NULL,entity_id INTEGER,details TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS idx_products_lookup ON products(name,generic,sku,barcode);
 CREATE INDEX IF NOT EXISTS idx_batches_fefo ON batches(product_id,expiry,remaining);
 CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(date);
 CREATE INDEX IF NOT EXISTS idx_purchases_date ON purchases(date);
 CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);
 CREATE INDEX IF NOT EXISTS idx_movements_time ON movements(created_at);
 CREATE INDEX IF NOT EXISTS idx_audit_time ON audit(created_at);
 `);if(!db.pragma('table_info(purchase_items)').some(c=>c.name==='returned'))db.exec('ALTER TABLE purchase_items ADD COLUMN returned INTEGER NOT NULL DEFAULT 0')}open();
 db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('appVersion',JSON.stringify(appVersion));
 const one=(sql,...args)=>db.prepare(sql).get(...args);const all=(sql,...args)=>db.prepare(sql).all(...args);
 const getSetting=k=>{const r=one('SELECT value FROM settings WHERE key=?',k);return r?JSON.parse(r.value):null};
 const setting=(k,v)=>db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,JSON.stringify(v));
 const audit=(u,a,e,eid,details={})=>db.prepare('INSERT INTO audit(user_id,action,entity,entity_id,details,created_at) VALUES(?,?,?,?,?,?)').run(u,a,e,eid,JSON.stringify(details),iso());
 const movement=(p,b,delta,before,reason,ref,u)=>db.prepare('INSERT INTO movements(product_id,batch_id,delta,before_qty,after_qty,reason,reference,user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(p,b,delta,before,before+delta,reason,ref,u,iso());
 const roles={Owner:['*'],Manager:['overview','products','inventory','purchases','suppliers','customers','sales','returns','expenses','reports','settings','backup','audit'],Cashier:['overview','products','sales','customers','returns'],Inventory:['overview','products','inventory','purchases','suppliers','reports'],Accountant:['overview','customers','suppliers','expenses','reports','payments']};
 const category={bootstrap:null,setup:null,login:null,logout:null,overview:'overview',listProducts:'products',listInventory:'inventory',saveProduct:'products',importProducts:'products',listBatches:'inventory',adjustStock:'inventory',expiry:'inventory',movements:'inventory',listSuppliers:'suppliers',saveSupplier:'suppliers',listCustomers:'customers',saveCustomer:'customers',purchase:'purchases',listPurchases:'purchases',getPurchase:'purchases',returnPurchase:'purchases',listPurchaseReturns:'purchases',sale:'sales',listSales:'sales',getSale:'sales',returnSale:'returns',listReturns:'returns',customerPayment:'customers',supplierPayment:'suppliers',listExpenses:'expenses',expense:'expenses',reports:'reports',getSettings:'settings',saveSettings:'settings',listUsers:'users',saveUser:'users',listAudit:'audit',backup:'backup',diagnosticLogs:'backup',listBackups:'backup',restore:'backup',demo:'products',deleteDemo:'products',search:'overview'};
 const restricted={saveProduct:['Owner','Manager','Inventory'],importProducts:['Owner','Manager','Inventory'],returnPurchase:['Owner','Manager','Inventory'],saveSettings:['Owner'],saveUser:['Owner'],listUsers:['Owner'],listAudit:['Owner','Manager'],backup:['Owner','Manager'],diagnosticLogs:['Owner','Manager'],restore:['Owner'],demo:['Owner'],deleteDemo:['Owner'],adjustStock:['Owner','Manager','Inventory'],returnSale:['Owner','Manager'],reports:['Owner','Manager','Inventory','Accountant']};
 function who(args,method){if(!(method in category))throw Error('Unknown action.');if(['bootstrap','setup','login'].includes(method))return null;const session=sessions.get(args._token);if(!session||Date.now()-session.at>8*60*60*1000){sessions.delete(args._token);throw Error('Your session has expired. Please sign in again.');}session.at=Date.now();const u=one('SELECT id,name,username,role,active FROM users WHERE id=?',session.id);if(!u||!u.active)throw Error('Account disabled.');if(method==='logout')return u;const c=category[method];if(!(roles[u.role]||[]).includes('*')&&!(roles[u.role]||[]).includes(c))throw Error('You do not have permission for this action.');if(restricted[method]&&!restricted[method].includes(u.role))throw Error('An authorized user is required for this action.');return u}
 function page(a){return Math.max(1,Math.min(10000,Number(a.page)||1))}const size=25;
 function productQuery(where='',params=[],a={}){const p=page(a);return {rows:all(`SELECT p.*,coalesce(sum(b.remaining),0) stock,min(CASE WHEN b.remaining>0 THEN b.expiry END) next_expiry FROM products p LEFT JOIN batches b ON p.id=b.product_id WHERE p.active=1 ${where} GROUP BY p.id ORDER BY p.name LIMIT ? OFFSET ?`,...params,size,(p-1)*size),total:one(`SELECT count(*) n FROM products p WHERE p.active=1 ${where}`,...params).n,page:p}};
 function execute(method,args={}){const u=who(args,method),uid=u?.id;
 switch(method){
 case 'bootstrap': return {installed:!!getSetting('store'),store:getSetting('store'),currency:getSetting('currency')||'PKR'};
 case 'setup':{if(getSetting('store'))throw Error('Setup is already complete.');let name=requireText(args.store,'Store name'),username=requireText(args.username,'Username');if(String(args.password||'').length<8)throw Error('Password must have at least 8 characters.');return db.transaction(()=>{setting('store',{name,address:text(args.address),phone:text(args.phone)});setting('currency',text(args.currency)||'PKR');setting('preferences',{expiryDays:30,reorder:10,receipt:'Thermal',automaticBackup:false});const r=db.prepare('INSERT INTO users(name,username,password_hash,role,created_at) VALUES(?,?,?,?,?)').run(requireText(args.name,'Administrator name'),username.toLowerCase(),hash(args.password),'Owner',iso());audit(r.lastInsertRowid,'setup','store',1);return true})();}
 case 'login':{const account=one('SELECT * FROM users WHERE username=? AND active=1',text(args.username).toLowerCase());if(!account||!check(String(args.password||''),account.password_hash))throw Error('Incorrect username or password.');const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{id:account.id,at:Date.now()});audit(account.id,'login','user',account.id);const response={token,user:{id:account.id,name:account.name,role:account.role},store:getSetting('store'),currency:getSetting('currency')||'PKR'};if(getSetting('preferences')?.automaticBackup&&getSetting('lastAutomaticBackup')!==day()){const file=path.join(backupDir,`medflow-auto-${day()}.sqlite`);return db.backup(file).then(()=>{setting('lastAutomaticBackup',day());const autos=fs.readdirSync(backupDir).filter(x=>/^medflow-auto-\d{4}-\d{2}-\d{2}\.sqlite$/.test(x)).sort().reverse();autos.slice(14).forEach(x=>fs.unlinkSync(path.join(backupDir,x)));return response}).catch(e=>{logError('automaticBackup',e);return response})}return response;}
 case 'logout':sessions.delete(args._token);return true;
 case 'getSettings':return {store:getSetting('store'),currency:getSetting('currency'),preferences:getSetting('preferences'),database:dbPath};
 case 'saveSettings':{const st={name:requireText(args.store?.name,'Store name'),address:text(args.store?.address),phone:text(args.store?.phone)};db.transaction(()=>{setting('store',st);setting('currency',text(args.currency)||'PKR');setting('preferences',{...getSetting('preferences'),...args.preferences});audit(uid,'update','settings',1)})();return true;}
 case 'saveSupplier':{const name=requireText(args.name,'Supplier name');return db.transaction(()=>{const values=[name,text(args.contact),text(args.phone),text(args.email),text(args.address),text(args.notes,1000)];let r;if(args.id){r=db.prepare('UPDATE suppliers SET name=?,contact=?,phone=?,email=?,address=?,notes=? WHERE id=?').run(...values,id(args.id));if(!r.changes)throw Error('Supplier not found.')}else r=db.prepare('INSERT INTO suppliers(name,contact,phone,email,address,notes,created_at) VALUES(?,?,?,?,?,?,?)').run(...values,iso());audit(uid,args.id?'update':'create','supplier',args.id||r.lastInsertRowid);return true})();}
 case 'listSuppliers':return all('SELECT s.*,coalesce((SELECT sum(due) FROM purchases WHERE supplier_id=s.id),0) balance,coalesce((SELECT sum(total) FROM purchases WHERE supplier_id=s.id),0) purchases FROM suppliers s ORDER BY name');
 case 'saveCustomer':{const name=requireText(args.name,'Customer name');return db.transaction(()=>{let r;const vals=[name,text(args.phone),text(args.email),text(args.address),cents(args.creditLimit||0),text(args.notes,1000)];if(args.id){r=db.prepare('UPDATE customers SET name=?,phone=?,email=?,address=?,credit_limit=?,notes=? WHERE id=?').run(...vals,id(args.id));if(!r.changes)throw Error('Customer not found.')}else r=db.prepare('INSERT INTO customers(name,phone,email,address,credit_limit,notes,created_at) VALUES(?,?,?,?,?,?,?)').run(...vals,iso());audit(uid,args.id?'update':'create','customer',args.id||r.lastInsertRowid);return true})();}
 case 'listCustomers':return all('SELECT * FROM customers ORDER BY name');
 case 'saveProduct':{const name=requireText(args.name,'Product name'),retail=cents(args.retail||0),purchase=cents(args.purchase||0);const vals=[name,text(args.generic),text(args.brand),text(args.manufacturer),text(args.category)||'General',text(args.sku)||null,text(args.barcode)||null,text(args.form)||'Other',text(args.strength),text(args.unit)||'unit',retail,purchase,Math.max(0,Number(args.reorder)||0),args.prescription?1:0,args.supplier_id? id(args.supplier_id):null];return db.transaction(()=>{let r;if(args.id){r=db.prepare('UPDATE products SET name=?,generic=?,brand=?,manufacturer=?,category=?,sku=?,barcode=?,form=?,strength=?,unit=?,retail=?,purchase=?,reorder=?,prescription=?,supplier_id=? WHERE id=?').run(...vals,id(args.id));if(!r.changes)throw Error('Product not found.')}else r=db.prepare('INSERT INTO products(name,generic,brand,manufacturer,category,sku,barcode,form,strength,unit,retail,purchase,reorder,prescription,supplier_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...vals,iso());audit(uid,args.id?'update':'create','product',args.id||r.lastInsertRowid);return true})();}
 case 'listProducts':{const q=text(args.q).toLowerCase();const result=productQuery(q?'AND (lower(p.name) LIKE ? OR lower(p.generic) LIKE ? OR lower(p.sku) LIKE ? OR lower(p.barcode) LIKE ?)':'',q?Array(4).fill('%'+q+'%'):[],args);if(u.role==='Cashier')result.rows=result.rows.map(({purchase,...r})=>r);return result}
 case 'importProducts':{if(!Array.isArray(args.rows)||!args.rows.length||args.rows.length>2000)throw Error('Choose a CSV with 1 to 2,000 product rows.');const problems=[],seenSku=new Set(),seenBar=new Set();const clean=args.rows.map((r,i)=>{const row={name:text(r.name),generic:text(r.generic),category:text(r.category)||'General',sku:text(r.sku)||null,barcode:text(r.barcode)||null,retail:0,purchase:0,reorder:0};const errs=[];if(!row.name)errs.push('name required');try{row.retail=cents(r.retail);row.purchase=cents(r.purchase||0);const n=Number(r.reorder||0);if(!Number.isSafeInteger(n)||n<0)throw Error();row.reorder=n}catch{errs.push('invalid price or reorder level')}if(row.sku){if(seenSku.has(row.sku)||one('SELECT id FROM products WHERE sku=?',row.sku))errs.push('duplicate SKU');seenSku.add(row.sku)}if(row.barcode){if(seenBar.has(row.barcode)||one('SELECT id FROM products WHERE barcode=?',row.barcode))errs.push('duplicate barcode');seenBar.add(row.barcode)}if(errs.length)problems.push({row:i+2,error:errs.join(', ')});return row});if(args.dryRun)return {valid:problems.length===0,count:clean.length,errors:problems.slice(0,30)};if(problems.length)throw Error(`Import blocked: ${problems.length} row(s) have errors. Preview and fix them first.`);return db.transaction(()=>{for(const r of clean)db.prepare('INSERT INTO products(name,generic,category,sku,barcode,retail,purchase,reorder,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(r.name,r.generic,r.category,r.sku,r.barcode,r.retail,r.purchase,r.reorder,iso());audit(uid,'import','products',null,{count:clean.length});return {count:clean.length}})()}

 case 'listInventory':{const p=page(args),low=args.low?1:0;const base='WITH stock AS (SELECT p.id,p.name,p.category,p.reorder,p.purchase,coalesce(sum(b.remaining),0) stock,coalesce(sum(b.remaining*b.cost),0) value,min(CASE WHEN b.remaining>0 THEN b.expiry END) next_expiry FROM products p LEFT JOIN batches b ON b.product_id=p.id WHERE p.active=1 GROUP BY p.id) ';return {rows:all(base+'SELECT * FROM stock WHERE (?=0 OR stock<=reorder) ORDER BY name LIMIT ? OFFSET ?',low,size,(p-1)*size),total:one(base+'SELECT count(*) n FROM stock WHERE (?=0 OR stock<=reorder)',low).n,page:p}}
 case 'listBatches':return all('SELECT b.*,p.name product,s.name supplier FROM batches b JOIN products p ON p.id=b.product_id LEFT JOIN suppliers s ON s.id=b.supplier_id WHERE (?=0 OR b.product_id=?) ORDER BY b.expiry LIMIT 200',Number(args.product_id)||0,Number(args.product_id)||0);
 case 'search':{const q=text(args.q).toLowerCase();if(!q)return [];return all("SELECT p.id,p.name,p.generic,p.barcode,p.sku,p.retail,p.prescription,p.unit,coalesce(sum(CASE WHEN b.expiry>=? THEN b.remaining ELSE 0 END),0) stock FROM products p LEFT JOIN batches b ON b.product_id=p.id WHERE p.active=1 AND (lower(p.name) LIKE ? OR lower(p.generic) LIKE ? OR lower(p.barcode)=? OR lower(p.sku)=?) GROUP BY p.id ORDER BY CASE WHEN lower(p.barcode)=? THEN 0 ELSE 1 END,p.name LIMIT 25",day(),'%'+q+'%','%'+q+'%',q,q,q)}
 case 'purchase':return db.transaction(()=>{const supplier=id(args.supplier_id);if(!one('SELECT id FROM suppliers WHERE id=?',supplier))throw Error('Select a supplier.');if(!Array.isArray(args.items)||!args.items.length)throw Error('Add at least one purchase item.');const invoice=requireText(args.invoice_no,'Supplier invoice number');let total=0;const rows=args.items.map(it=>{const p=one('SELECT * FROM products WHERE id=? AND active=1',id(it.product_id));if(!p)throw Error('Choose a valid product.');const n=qty(it.quantity),cost=cents(it.cost),price=cents(it.price),expiry=text(it.expiry),batch=requireText(it.batch_no,'Batch number');if(!/^\d{4}-\d{2}-\d{2}$/.test(expiry)||expiry<day())throw Error('Batch expiry must be a valid future date.');if(price<cost)throw Error('Selling price cannot be lower than purchase cost.');total+=cost*n;return {p,n,cost,price,expiry,batch}});const paid=cents(args.paid||0);if(paid>total)throw Error('Paid amount exceeds purchase total.');const due=total-paid;const r=db.prepare('INSERT INTO purchases(invoice_no,supplier_id,date,total,paid,due,user_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run(invoice,supplier,text(args.date)||day(),total,paid,due,uid,iso());for(const it of rows){let b=one('SELECT * FROM batches WHERE product_id=? AND batch_no=? AND expiry=?',it.p.id,it.batch,it.expiry);let batchId,before=0;if(b){batchId=b.id;before=b.remaining;db.prepare('UPDATE batches SET remaining=remaining+?,initial_qty=initial_qty+?,cost=?,price=? WHERE id=?').run(it.n,it.n,it.cost,it.price,batchId)}else{batchId=db.prepare('INSERT INTO batches(product_id,supplier_id,batch_no,expiry,purchased_on,cost,price,initial_qty,remaining) VALUES(?,?,?,?,?,?,?,?,?)').run(it.p.id,supplier,it.batch,it.expiry,day(),it.cost,it.price,it.n,it.n).lastInsertRowid}db.prepare('INSERT INTO purchase_items(purchase_id,batch_id,product_id,quantity,cost,price) VALUES(?,?,?,?,?,?)').run(r.lastInsertRowid,batchId,it.p.id,it.n,it.cost,it.price);movement(it.p.id,batchId,it.n,before,'purchase',invoice,uid)}if(paid)db.prepare('INSERT INTO payments(kind,reference_id,amount,method,date,user_id) VALUES(?,?,?,?,?,?)').run('purchase',r.lastInsertRowid,paid,text(args.method)||'Cash',day(),uid);audit(uid,'create','purchase',r.lastInsertRowid,{invoice,total});return {id:r.lastInsertRowid,total,due}})();
 case 'listPurchases':return all('SELECT p.*,s.name supplier,u.name employee FROM purchases p JOIN suppliers s ON s.id=p.supplier_id JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 200');
 case 'getPurchase':{const pur=one('SELECT p.*,s.name supplier FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.id=?',id(args.id));if(!pur)throw Error('Purchase not found.');return {purchase:pur,items:all('SELECT pi.*,pr.name,b.batch_no,b.remaining FROM purchase_items pi JOIN products pr ON pr.id=pi.product_id JOIN batches b ON b.id=pi.batch_id WHERE pi.purchase_id=?',pur.id)}}
 case 'returnPurchase':return db.transaction(()=>{const it=one('SELECT pi.*,p.invoice_no,p.supplier_id,p.due FROM purchase_items pi JOIN purchases p ON p.id=pi.purchase_id WHERE pi.id=?',id(args.item_id));if(!it)throw Error('Purchase line not found.');const n=qty(args.quantity);if(n>it.quantity-it.returned)throw Error('Return quantity exceeds available purchased units.');const batch=one('SELECT * FROM batches WHERE id=?',it.batch_id);if(n>batch.remaining)throw Error(`Only ${batch.remaining} units remain in this batch. Sold units cannot be returned to the supplier.`);const reason=requireText(args.reason,'Return reason'),amount=n*it.cost,applied=Math.min(it.due,amount),refund=amount-applied;db.prepare('UPDATE batches SET remaining=remaining-? WHERE id=?').run(n,batch.id);db.prepare('UPDATE purchase_items SET returned=returned+? WHERE id=?').run(n,it.id);db.prepare('UPDATE purchases SET due=due-?,paid=paid-?,total=total-? WHERE id=?').run(applied,refund,amount,it.purchase_id);const r=db.prepare('INSERT INTO purchase_returns(purchase_id,purchase_item_id,quantity,amount,refund,credit_applied,reason,date,user_id) VALUES(?,?,?,?,?,?,?,?,?)').run(it.purchase_id,it.id,n,amount,refund,applied,reason,day(),uid);movement(it.product_id,it.batch_id,-n,batch.remaining,'purchase return',it.invoice_no,uid);audit(uid,'return','purchase',it.purchase_id,{quantity:n,amount});return {id:r.lastInsertRowid,refund,creditApplied:applied}})();
 case 'listPurchaseReturns':return all('SELECT r.*,p.invoice_no,pr.name product FROM purchase_returns r JOIN purchases p ON p.id=r.purchase_id JOIN purchase_items pi ON pi.id=r.purchase_item_id JOIN products pr ON pr.id=pi.product_id ORDER BY r.id DESC LIMIT 100');

 case 'sale':return db.transaction(()=>{if(!Array.isArray(args.items)||!args.items.length)throw Error('Cart is empty.');let subtotal=0;const allocations=[];for(const it of args.items){const p=one('SELECT * FROM products WHERE id=? AND active=1',id(it.product_id));if(!p)throw Error('A cart product no longer exists.');if(p.prescription&&!args.prescriptionConfirmed)throw Error(`${p.name} requires prescription confirmation before sale.`);const n=qty(it.quantity);let left=n;const batches=all('SELECT * FROM batches WHERE product_id=? AND remaining>0 AND expiry>=? ORDER BY expiry,id',p.id,day());for(const b of batches){const take=Math.min(left,b.remaining);if(take){allocations.push({p,b,take});left-=take}if(!left)break}if(left)throw Error(`${p.name} has only ${n-left} saleable units available. Check stock or expiry.`);subtotal+=p.retail*n}const discount=cents(args.discount||0),tax=cents(args.tax||0);if(discount>subtotal)throw Error('Discount cannot exceed subtotal.');const total=subtotal-discount+tax,paid=cents(args.paid??(total/100));if(paid>total&&args.method!=='Cash')throw Error('Overpayment is only supported for cash.');const due=Math.max(0,total-paid);const customer=args.customer_id?id(args.customer_id):null;if(due&&!customer)throw Error('Select a customer for a partial or credit sale.');if(customer){const c=one('SELECT * FROM customers WHERE id=?',customer);if(!c)throw Error('Customer not found.');if(due&&c.credit_limit&&c.balance+due>c.credit_limit)throw Error('This sale exceeds the customer credit limit.')}const invoice='MF-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase();const r=db.prepare('INSERT INTO sales(invoice_no,customer_id,date,subtotal,discount,tax,total,paid,due,method,user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(invoice,customer,day(),subtotal,discount,tax,total,Math.min(paid,total),due,text(args.method)||'Cash',uid,iso());for(const {p,b,take} of allocations){const changed=db.prepare('UPDATE batches SET remaining=remaining-? WHERE id=? AND remaining>=?').run(take,b.id,take);if(!changed.changes)throw Error('Stock changed while completing the sale. Please try again.');db.prepare('INSERT INTO sale_items(sale_id,product_id,batch_id,quantity,price,cost) VALUES(?,?,?,?,?,?)').run(r.lastInsertRowid,p.id,b.id,take,p.retail,b.cost);movement(p.id,b.id,-take,b.remaining,'sale',invoice,uid)}if(due)db.prepare('UPDATE customers SET balance=balance+? WHERE id=?').run(due,customer);if(paid)db.prepare('INSERT INTO payments(kind,reference_id,customer_id,amount,method,date,user_id) VALUES(?,?,?,?,?,?,?)').run('sale',r.lastInsertRowid,customer,Math.min(paid,total),text(args.method)||'Cash',day(),uid);audit(uid,'create','sale',r.lastInsertRowid,{invoice,total});return {id:r.lastInsertRowid,invoice_no:invoice,total,due,change:Math.max(0,paid-total)}})();
 case 'listSales':return all('SELECT s.*,coalesce(c.name,\'Walk-in\') customer,u.name cashier FROM sales s LEFT JOIN customers c ON c.id=s.customer_id JOIN users u ON u.id=s.user_id ORDER BY s.id DESC LIMIT 200');
 case 'getSale':{const sale=one('SELECT s.*,coalesce(c.name,\'Walk-in\') customer,u.name cashier FROM sales s LEFT JOIN customers c ON c.id=s.customer_id JOIN users u ON u.id=s.user_id WHERE s.id=?',id(args.id));if(!sale)throw Error('Invoice not found.');const items=all('SELECT si.*,p.name,b.batch_no FROM sale_items si JOIN products p ON p.id=si.product_id JOIN batches b ON b.id=si.batch_id WHERE si.sale_id=?',sale.id);return {sale,items:u.role==='Cashier'?items.map(({cost,...r})=>r):items,store:getSetting('store'),currency:getSetting('currency')}}
 case 'returnSale':return db.transaction(()=>{const it=one('SELECT si.*,s.customer_id,s.due,s.invoice_no FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE si.id=?',id(args.item_id));if(!it)throw Error('Sale item not found.');const n=qty(args.quantity);if(n>it.quantity-it.returned)throw Error('Return quantity exceeds the quantity sold minus previous returns.');const reason=requireText(args.reason,'Return reason');const sale=one('SELECT * FROM sales WHERE id=?',it.sale_id);const gross=sale.subtotal?Math.round((it.price*n)*((sale.subtotal-sale.discount+sale.tax)/sale.subtotal)):0;const applied=Math.min(sale.due,gross),refund=gross-applied;const b=one('SELECT remaining FROM batches WHERE id=?',it.batch_id);db.prepare('UPDATE batches SET remaining=remaining+? WHERE id=?').run(n,it.batch_id);db.prepare('UPDATE sale_items SET returned=returned+? WHERE id=?').run(n,it.id);db.prepare('UPDATE sales SET due=due-?,paid=paid-?,total=total-? WHERE id=?').run(applied,refund,gross,sale.id);if(applied)db.prepare('UPDATE customers SET balance=balance-? WHERE id=?').run(applied,it.customer_id);const r=db.prepare('INSERT INTO returns(sale_id,sale_item_id,quantity,amount,refund,credit_applied,reason,date,user_id) VALUES(?,?,?,?,?,?,?,?,?)').run(sale.id,it.id,n,gross,refund,applied,reason,day(),uid);movement(it.product_id,it.batch_id,n,b.remaining,'return',it.invoice_no,uid);audit(uid,'return','sale',sale.id,{quantity:n,amount:gross});return {id:r.lastInsertRowid,refund,creditApplied:applied}})();
 case 'listReturns':return all('SELECT r.*,s.invoice_no,p.name product FROM returns r JOIN sales s ON s.id=r.sale_id JOIN sale_items si ON si.id=r.sale_item_id JOIN products p ON p.id=si.product_id ORDER BY r.id DESC LIMIT 100');
 case 'customerPayment':return db.transaction(()=>{const c=one('SELECT * FROM customers WHERE id=?',id(args.customer_id));if(!c)throw Error('Customer not found.');const amount=cents(args.amount);if(!amount||amount>c.balance)throw Error('Payment must be greater than zero and cannot exceed outstanding balance.');db.prepare('UPDATE customers SET balance=balance-? WHERE id=?').run(amount,c.id);let remaining=amount;for(const sale of all('SELECT id,due FROM sales WHERE customer_id=? AND due>0 ORDER BY id',c.id)){const applied=Math.min(remaining,sale.due);db.prepare('UPDATE sales SET due=due-?,paid=paid+? WHERE id=?').run(applied,applied,sale.id);remaining-=applied;if(!remaining)break}if(remaining)throw Error('Credit ledger is inconsistent. Please contact support.');const r=db.prepare('INSERT INTO payments(kind,reference_id,customer_id,amount,method,date,user_id) VALUES(?,?,?,?,?,?,?)').run('customer',c.id,c.id,amount,text(args.method)||'Cash',day(),uid);audit(uid,'payment','customer',c.id,{amount});return {id:r.lastInsertRowid}})();
 case 'supplierPayment':return db.transaction(()=>{const supplier=one('SELECT * FROM suppliers WHERE id=?',id(args.supplier_id));if(!supplier)throw Error('Supplier not found.');const outstanding=one('SELECT coalesce(sum(due),0) n FROM purchases WHERE supplier_id=?',supplier.id).n;const amount=cents(args.amount);if(!amount||amount>outstanding)throw Error('Payment must be greater than zero and cannot exceed outstanding balance.');let remaining=amount;for(const pur of all('SELECT id,due FROM purchases WHERE supplier_id=? AND due>0 ORDER BY id',supplier.id)){const applied=Math.min(remaining,pur.due);db.prepare('UPDATE purchases SET due=due-?,paid=paid+? WHERE id=?').run(applied,applied,pur.id);remaining-=applied;if(!remaining)break}const r=db.prepare('INSERT INTO payments(kind,reference_id,amount,method,date,user_id) VALUES(?,?,?,?,?,?)').run('supplier',supplier.id,amount,text(args.method)||'Cash',day(),uid);audit(uid,'payment','supplier',supplier.id,{amount});return {id:r.lastInsertRowid}})();
 case 'adjustStock':return db.transaction(()=>{const b=one('SELECT * FROM batches WHERE id=?',id(args.batch_id));if(!b)throw Error('Batch not found.');const delta=Number(args.delta);if(!Number.isSafeInteger(delta)||!delta||b.remaining+delta<0)throw Error('Enter a valid adjustment; available stock cannot go below zero.');const reason=requireText(args.reason,'Adjustment reason');db.prepare('UPDATE batches SET remaining=remaining+? WHERE id=?').run(delta,b.id);movement(b.product_id,b.id,delta,b.remaining,'adjustment',reason,uid);audit(uid,'adjust','batch',b.id,{delta,reason});return true})();
 case 'movements':return all('SELECT m.*,p.name product,b.batch_no,u.name employee FROM movements m JOIN products p ON p.id=m.product_id JOIN batches b ON b.id=m.batch_id JOIN users u ON u.id=m.user_id ORDER BY m.id DESC LIMIT 200');
 case 'expiry':return all('SELECT b.*,p.name product,s.name supplier,(b.remaining*b.cost) value FROM batches b JOIN products p ON p.id=b.product_id LEFT JOIN suppliers s ON s.id=b.supplier_id WHERE b.remaining>0 ORDER BY b.expiry LIMIT 500');
 case 'expense':return db.transaction(()=>{const r=db.prepare('INSERT INTO expenses(date,category,description,amount,method,user_id,created_at) VALUES(?,?,?,?,?,?,?)').run(text(args.date)||day(),requireText(args.category,'Category'),requireText(args.description,'Description'),cents(args.amount),text(args.method)||'Cash',uid,iso());audit(uid,'create','expense',r.lastInsertRowid);return true})();
 case 'listExpenses':return all('SELECT e.*,u.name employee FROM expenses e JOIN users u ON u.id=e.user_id ORDER BY e.id DESC LIMIT 200');
 case 'overview':{const from=text(args.from)||day(),to=text(args.to)||day();const summary=one(`SELECT coalesce(sum(total),0) sales, count(*) transactions, coalesce(sum(discount),0) discounts FROM sales WHERE date BETWEEN ? AND ?`,from,to);const cogs=one('SELECT coalesce(sum((si.quantity-si.returned)*si.cost),0) n FROM sale_items si JOIN sales s ON s.id=si.sale_id WHERE s.date BETWEEN ? AND ?',from,to).n;const expenses=one('SELECT coalesce(sum(amount),0) n FROM expenses WHERE date BETWEEN ? AND ?',from,to).n;const stock=one('SELECT count(*) products,coalesce(sum(stock),0) units,coalesce(sum(value),0) value,sum(CASE WHEN stock<=reorder AND stock>0 THEN 1 ELSE 0 END) low,sum(CASE WHEN stock=0 THEN 1 ELSE 0 END) out FROM (SELECT p.id,p.purchase,p.reorder,coalesce(sum(b.remaining),0) stock,coalesce(sum(b.remaining*b.cost),0) value FROM products p LEFT JOIN batches b ON b.product_id=p.id WHERE p.active=1 GROUP BY p.id)');const exp=one("SELECT sum(CASE WHEN expiry<? THEN 1 ELSE 0 END) expired,sum(CASE WHEN expiry>=? AND expiry<=date(?,'+30 days') THEN 1 ELSE 0 END) soon FROM batches WHERE remaining>0",day(),day(),day());const trend=all('SELECT date, sum(total) sales FROM sales WHERE date BETWEEN ? AND ? GROUP BY date ORDER BY date',from,to);const activity=all("SELECT 'sale' type,invoice_no label,total amount,created_at at FROM sales UNION ALL SELECT 'purchase',invoice_no,total,created_at FROM purchases UNION ALL SELECT 'expense',description,amount,created_at FROM expenses ORDER BY at DESC LIMIT 8");const masked=['Cashier','Inventory'].includes(u.role);if(masked)stock.value=null;return {summary:{...summary,cogs:masked?null:cogs,expenses:masked?null:expenses,profit:masked?null:summary.sales-cogs-expenses,receivables:masked?null:one('SELECT coalesce(sum(balance),0) n FROM customers').n,payables:masked?null:one('SELECT coalesce(sum(due),0) n FROM purchases').n},stock,expiry:exp,trend,activity:masked?activity.filter(x=>x.type==='sale'):activity,from,to};}
 case 'reports':{const from=text(args.from)||day(),to=text(args.to)||day(),type=text(args.type)||'sales';if(type==='sales')return all('SELECT s.date,s.invoice_no,coalesce(c.name,\'Walk-in\') customer,u.name employee,s.total,s.paid,s.due,s.method FROM sales s LEFT JOIN customers c ON c.id=s.customer_id JOIN users u ON u.id=s.user_id WHERE s.date BETWEEN ? AND ? ORDER BY s.id DESC LIMIT 5000',from,to);if(type==='stock')return all('SELECT p.name,p.sku,p.category,b.batch_no,b.expiry,b.remaining,b.cost,b.remaining*b.cost value FROM batches b JOIN products p ON p.id=b.product_id WHERE b.remaining>0 ORDER BY p.name,b.expiry LIMIT 5000');if(type==='expenses')return all('SELECT date,category,description,amount,method FROM expenses WHERE date BETWEEN ? AND ? ORDER BY id DESC LIMIT 5000',from,to);if(type==='purchases')return all('SELECT p.date,p.invoice_no,s.name supplier,p.total,p.paid,p.due FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.date BETWEEN ? AND ? ORDER BY p.id DESC LIMIT 5000',from,to);
 if(type==='daily')return all('SELECT date,count(*) transactions,sum(total) revenue,sum(paid) received,sum(due) outstanding FROM sales WHERE date BETWEEN ? AND ? GROUP BY date ORDER BY date DESC LIMIT 5000',from,to);
 if(type==='paymentMethods')return all('SELECT method,count(*) transactions,sum(total) sales,sum(paid) paid FROM sales WHERE date BETWEEN ? AND ? GROUP BY method ORDER BY sales DESC',from,to);
 if(type==='topProducts')return all('SELECT p.name,p.category,sum(si.quantity-si.returned) units,sum((si.quantity-si.returned)*si.price) gross_sales FROM sale_items si JOIN sales s ON s.id=si.sale_id JOIN products p ON p.id=si.product_id WHERE s.date BETWEEN ? AND ? GROUP BY p.id ORDER BY gross_sales DESC LIMIT 5000',from,to);
 if(type==='categories')return all('SELECT p.category,sum(si.quantity-si.returned) units,sum((si.quantity-si.returned)*si.price) gross_sales FROM sale_items si JOIN sales s ON s.id=si.sale_id JOIN products p ON p.id=si.product_id WHERE s.date BETWEEN ? AND ? GROUP BY p.category ORDER BY gross_sales DESC',from,to);
 if(type==='employees')return all('SELECT u.name employee,count(*) transactions,sum(s.total) sales FROM sales s JOIN users u ON u.id=s.user_id WHERE s.date BETWEEN ? AND ? GROUP BY u.id ORDER BY sales DESC',from,to);
 if(type==='expiry')return all(`SELECT p.name,b.batch_no,b.expiry,b.remaining,b.remaining*b.cost value,coalesce(s.name,'—') supplier FROM batches b JOIN products p ON p.id=b.product_id LEFT JOIN suppliers s ON s.id=b.supplier_id WHERE b.remaining>0 AND b.expiry<=date(?,'+90 days') ORDER BY b.expiry LIMIT 5000`,day());
 if(type==='lowStock')return all('SELECT p.name,p.sku,p.reorder,coalesce(sum(b.remaining),0) units FROM products p LEFT JOIN batches b ON b.product_id=p.id WHERE p.active=1 GROUP BY p.id HAVING units<=p.reorder ORDER BY units,p.name LIMIT 5000');
 if(type==='receivables')return all('SELECT name,phone,balance FROM customers WHERE balance>0 ORDER BY balance DESC LIMIT 5000');
 if(type==='payables')return all('SELECT s.name supplier,p.invoice_no,p.date,p.due FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.due>0 ORDER BY p.date LIMIT 5000');
 if(type==='movements')return all('SELECT m.created_at,p.name product,b.batch_no,m.delta,m.before_qty,m.after_qty,m.reason,m.reference FROM movements m JOIN products p ON p.id=m.product_id JOIN batches b ON b.id=m.batch_id WHERE substr(m.created_at,1,10) BETWEEN ? AND ? ORDER BY m.id DESC LIMIT 5000',from,to);throw Error('Unknown report type.')}
 case 'listUsers':return all('SELECT id,name,username,role,active,created_at FROM users ORDER BY id');
 case 'saveUser':return db.transaction(()=>{const role=text(args.role);if(!Object.hasOwn(roles,role))throw Error('Select a valid role.');if(args.id){const target=one('SELECT * FROM users WHERE id=?',id(args.id));if(!target)throw Error('User not found.');if(target.id===uid&&(!args.active||role!=='Owner'))throw Error('You cannot remove your own owner access.');db.prepare('UPDATE users SET name=?,role=?,active=? WHERE id=?').run(requireText(args.name,'Name'),role,args.active?1:0,target.id);if(args.password){if(args.password.length<8)throw Error('Password must have at least 8 characters.');db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hash(args.password),target.id)}audit(uid,'update','user',target.id);return true}if(String(args.password||'').length<8)throw Error('Password must have at least 8 characters.');const r=db.prepare('INSERT INTO users(name,username,password_hash,role,created_at) VALUES(?,?,?,?,?)').run(requireText(args.name,'Name'),requireText(args.username,'Username').toLowerCase(),hash(args.password),role,iso());audit(uid,'create','user',r.lastInsertRowid);return true})();
 case 'listAudit':return all('SELECT a.*,u.name employee FROM audit a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 300');
 case 'diagnosticLogs':{const file=path.join(root,'logs','medflow.log');return fs.existsSync(file)?fs.readFileSync(file,'utf8').slice(-100000):'No errors have been logged.'}
 case 'backup':{const name='medflow-'+iso().replace(/[:.]/g,'-')+'.sqlite';return db.backup(path.join(backupDir,name)).then(()=>{audit(uid,'backup','database',null,{name});return {name}})}
 case 'listBackups':return fs.readdirSync(backupDir).filter(x=>/^medflow-[\w-]+\.sqlite$/.test(x)).sort().reverse().map(name=>({name,size:fs.statSync(path.join(backupDir,name)).size}));
 case 'restore':{const name=text(args.name);if(!/^medflow-[\w-]+\.sqlite$/.test(name))throw Error('Select a backup from this computer.');if(args.confirm!=='RESTORE')throw Error('Type RESTORE to confirm.');const source=path.join(backupDir,name);if(!fs.existsSync(source))throw Error('Backup file not found.');const checkDb=new Database(source,{readonly:true,fileMustExist:true});const integrity=checkDb.pragma('integrity_check',{simple:true});checkDb.close();if(integrity!=='ok')throw Error('Backup failed its integrity check.');return db.backup(path.join(backupDir,'medflow-safety-'+iso().replace(/[:.]/g,'-')+'.sqlite')).then(()=>{db.close();fs.copyFileSync(source,dbPath);db=new Database(dbPath);open();sessions.clear();return true})}
 case 'demo':return db.transaction(()=>{if(one("SELECT id FROM products WHERE sku LIKE 'DEMO-%' LIMIT 1"))throw Error('Demo products are already loaded.');const supplier=db.prepare('INSERT INTO suppliers(name,contact,created_at) VALUES(?,?,?)').run('Demo Medical Distributors','Sample record',iso()).lastInsertRowid;const names=[['Paracetamol 500mg','Analgesics',85,48],['Ibuprofen 200mg','Pain relief',120,70],['Amoxicillin 250mg','Antibiotics',280,190],['Cetirizine 10mg','Allergy',95,52],['Omeprazole 20mg','Digestive',180,110],['Cough Syrup 120ml','Respiratory',210,135],['Vitamin C 500mg','Supplements',150,88],['Surgical Gloves','Medical supplies',40,22]];for(let i=0;i<names.length;i++){const [name,cat,retail,cost]=names[i];const r=db.prepare('INSERT INTO products(name,category,retail,purchase,sku,barcode,form,reorder,supplier_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(name,cat,retail*100,cost*100,'DEMO-'+(i+1),'89000000'+String(i+1).padStart(5,'0'),i===5?'Syrup':'Tablet',12,supplier,iso());const expiry=new Date();expiry.setMonth(expiry.getMonth()+2+i);const exp=expiry.toISOString().slice(0,10);const b=db.prepare('INSERT INTO batches(product_id,supplier_id,batch_no,expiry,purchased_on,cost,price,initial_qty,remaining) VALUES(?,?,?,?,?,?,?,?,?)').run(r.lastInsertRowid,supplier,'DEMO-B'+(i+1),exp,day(),cost*100,retail*100,25+i*4,25+i*4);movement(r.lastInsertRowid,b.lastInsertRowid,25+i*4,0,'demo','DEMO',uid)}audit(uid,'load','demo',null);return true})();
 case 'deleteDemo':return db.transaction(()=>{const items=all("SELECT id FROM products WHERE sku LIKE 'DEMO-%'");for(const p of items){if(one('SELECT id FROM sale_items WHERE product_id=? LIMIT 1',p.id)||one('SELECT id FROM purchase_items WHERE product_id=? LIMIT 1',p.id))throw Error('Demo products have transaction history and cannot be removed safely.');db.prepare('DELETE FROM movements WHERE product_id=?').run(p.id);db.prepare('DELETE FROM batches WHERE product_id=?').run(p.id);db.prepare('DELETE FROM products WHERE id=?').run(p.id)}db.prepare("DELETE FROM suppliers WHERE name='Demo Medical Distributors' AND NOT EXISTS(SELECT 1 FROM purchases WHERE supplier_id=suppliers.id)").run();audit(uid,'remove','demo',null);return true})();
 default:throw Error('Unknown action.');
 }}
 function call(method,args={}){try{const result=execute(method,args);return result&&typeof result.then==='function'?result.catch(e=>{logError(method,e);throw e}):result}catch(e){logError(method,e);throw e}}
 return {call,backupDir,dbPath,close(){sessions.clear();db.close()}};
}
module.exports={createService};
